### ISSUE TITLE
Performance regression with rust 1.52.0

### ISSUE THREAD

**Issue by marmeladema** [cloudflare/sliceslice-rs#47]
Rust 1.51.0:
```
short_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1010073463 instructions 1010073466 instructions 1010073469 instructions]
long_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [237648142 instructions 237648143 instructions 237648144 instructions]
random_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1563190 instructions 1563190 instructions 1563190 instructions]
```

Rust 1.52.0:
```
short_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1233359721 instructions 1233359723 instructions 1233359726 instructions]
long_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [237719727 instructions 237719730 instructions 237719734 instructions]
random_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1567493 instructions 1567493 instructions 1567493 instructions]
```

Summary:
* short: +22%
* long: +0%
* random: +0%

**Comment by marmeladema** [comment]
cc @zakcutner 
Would you happen to have an idea on how to pin-point where the regression is actually coming from?

**Comment by zakcutner** [comment]
Ah that's weird, I can try profiling using both versions of the compiler to see if that shows up any significant differences.

**Comment by marmeladema** [comment]
Using `readelf` I tried to check for any substantial size for `sliceslice` symbols.

* Rust 1.51.0:
```
$ readelf -s --wide target/release/examples/grep | rustfilt  | grep sliceslice
    56: 0000000000007180 12127 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::inlined_search_in
    68: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS sliceslice.7x3guuyw-cgu.0
   683: 0000000000006170  4112 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::new
   935: 000000000000a710     3 FUNC    GLOBAL DEFAULT   14 sliceslice::MemchrSearcher::new
```

* Rust 1.52.0:
```
$ readelf -s --wide target/release/examples/grep | rustfilt  | grep sliceslice
   413: 0000000000008b70 12453 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::inlined_search_in
   426: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS sliceslice.wojh9lmw-cgu.0
   491: 0000000000007c50  3857 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::new
   670: 000000000000c230     3 FUNC    GLOBAL DEFAULT   14 sliceslice::MemchrSearcher::new
```

That's a 2.5% increase in instruction count for our main search method. I am not sure if it can explain such a difference in the benchmarks. Additionally, `grep` binary (see https://github.com/cloudflare/sliceslice-rs/tree/grep-example branch) is probably not compiled with the same options as the benchmarks, so it might be interesting to try tweaking the options a bit.

**Comment by marmeladema** [comment]
Now with `codegen-units = 1` and `lto = true`:

* Rust 1.51.0:

```
$ readelf -s --wide target/release/examples/grep | rustfilt  | grep sliceslice
   105: 0000000000004150 12119 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::inlined_search_in
   106: 00000000000070b0  3976 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::new
```

* Rust 1.52.0:

```
$ readelf -s --wide target/release/examples/grep | rustfilt  | grep sliceslice
    94: 0000000000005b20 12440 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::inlined_search_in
    95: 0000000000008bc0  3698 FUNC    LOCAL  DEFAULT   14 sliceslice::x86::DynamicAvx2Searcher<N>::new
```

Same increase of 2.5% for `inlined_search_in`

**Comment by marmeladema** [comment]
Also, because it's the `short_haystack` benchmark that has regressed, we might be able to assume it's related to the scalar searcher since it's mostly what is being tested here.

**Comment by BurntSushi** [comment]
Yes, I'm able to reproduce it in my harness too. I ran

```
$ cargo +1.51.0 bench -- 'memmem/(krate|sliceslice)/prebuilt/sliceslice-' --save-baseline rust1510
$ cargo +1.52.0 bench -- 'memmem/(krate|sliceslice)/prebuilt/sliceslice-' --save-baseline rust1520
```

and then to compare

```
$ critcmp rust1510 rust1520
group                                                   rust1510                               rust1520
-----                                                   --------                               --------
memmem/krate/prebuilt/sliceslice-haystack/words         1.10    196.1±0.27µs        0 B/sec    1.00    178.5±0.30µs        0 B/sec
memmem/krate/prebuilt/sliceslice-i386/words             1.07     24.9±0.03ms        0 B/sec    1.00     23.2±0.03ms        0 B/sec
memmem/krate/prebuilt/sliceslice-words/words            1.00     77.0±0.06ms        0 B/sec    1.06     81.5±0.12ms        0 B/sec
memmem/sliceslice/prebuilt/sliceslice-haystack/words    1.01    169.7±0.33µs        0 B/sec    1.00    168.9±0.18µs        0 B/sec
memmem/sliceslice/prebuilt/sliceslice-i386/words        1.01     26.6±0.05ms        0 B/sec    1.00     26.4±0.04ms        0 B/sec
memmem/sliceslice/prebuilt/sliceslice-words/words       1.00     68.7±0.07ms        0 B/sec    1.22     83.7±0.08ms        0 B/sec
```

Looking at a profile, I can't immediately spot an obvious explanation for the change in your `short_haystack` benchmark. The codegen is definitely different. Looking at my biggest change (an improvement in your `random` benchmark), profiling reveals the difference is likely explained by better codegen of the main loop. Basically, the same thing I talked about in this comment: https://github.com/cloudflare/sliceslice-rs/pull/26#issuecomment-831404112

Note that I believe Rust 1.52 included an LLVM upgrade, so that could have changed things.

**Comment by zakcutner** [comment]
@marmeladema I seem to get more consistent time-based benchmarks than you so I've run both those and the instruction ones. Here are the results for 1.51.0...

```
short_haystack/DynamicAvx2Searcher::search_in                        
                        time:   [88.543 ms 88.741 ms 88.953 ms]
short_haystack/DynamicAvx2Searcher::search_in                        
                        time:   [1010073349 instructions 1010073350 instructions 1010073350 instructions]
```

...and for 1.52.0...

```
short_haystack/DynamicAvx2Searcher::search_in                        
                        time:   [88.370 ms 88.483 ms 88.629 ms]
short_haystack/DynamicAvx2Searcher::search_in                        
                        time:   [1233359620 instructions 1233359620 instructions 1233359621 instructions]
```

As you can see, I get a similar regression in the number of instructions after updating to 1.52.0. However, the execution time does not regress and in fact improves slightly. As @BurntSushi said, I saw that LLVM was updated to version 12 which would probably explain this.

I'm therefore thinking that this is probably not an issue, but what do you think? I also did try profiling both versions and comparing although there didn't seem to be a major difference. However, the binaries do look quite different and I think generally we should be careful about only using instruction counts. Looking briefly at some hot sections of code, 1.52.0 seems to use more auto-vectorization before among other changes. For this, it uses more instructions to achieve the same functionality although overall this is presumably more efficient than the scalar code generated by 1.51.0.

As a guess for why we see this effect for short haystacks particularly, as you suggested I wonder if it is because the Rabin-Karp fallback is more likely to be used in this case. Since it is one of the few methods we have not manually vectorized, perhaps compiler auto-vectorization could be especially prevalent here.

**Comment by marmeladema** [comment]
> However, the execution time does not regress and in fact improves slightly.

But @BurntSushi was able to reproduce the regression in term of timings by about the same amount of magnitude that the instruction count regression I noticed:

```
group                                                   rust1510                               rust1520
-----                                                   --------                               --------
memmem/sliceslice/prebuilt/sliceslice-words/words       1.00     68.7±0.07ms        0 B/sec    1.22     83.7±0.08ms        0 B/sec
```

Around +22% time and instruction. This does not seem right to me. I initially started investigating this because I run our internal benchmark against rust 1.52.0, I noticed huge regressions in instruction count and smaller, but still regressions in terms of wall clock time.

**Comment by zakcutner** [comment]
Sorry, I hadn't understood that but it's definitely interesting. I'll take a look at that benchmark and see if I can find anything more.

**Comment by marmeladema** [comment]
I have landed a couple of optimizations that are reducing the regression to 18%.

**Comment by marmeladema** [comment]
Ok with https://github.com/cloudflare/sliceslice-rs/pull/50 merged, we should be down at a 7.35% regression between both rust versions.

**Comment by marmeladema** [comment]
I found a way to entirely get rid of the scalar searcher which is responsible for the regression. It actually improves performances for the short benchmarks of around another 10% and give identical results for both rust versions.

**Comment by marmeladema** [comment]
Version 0.3.1 has just been published and should mitigate the regression introduced by rust 1.52.x

Rust 1.51.0:
```
short_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [764314307 instructions 764314308 instructions 764314309 instructions]
long_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [236983885 instructions 236983886 instructions 236983886 instructions]
random_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1588582 instructions 1588582 instructions 1588582 instructions]
```

Rust 1.52.1:
```
short_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [764314324 instructions 764314326 instructions 764314328 instructions]
long_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [236983892 instructions 236983892 instructions 236983893 instructions]
random_haystack/DynamicAvx2Searcher::search_in #2
                        time:   [1588582 instructions 1588582 instructions 1588582 instructions]
```

Summary:
* short: +0%
* long: +0%
* random: +0%
