### ISSUE TITLE
@kodster28

### ISSUE THREAD

**Issue by Nuttapon43** [cloudflare/sliceslice-rs#77]
@kodster28

_Originally posted by @Nuttapon43 in https://github.com/cloudflare/cloudflare-docs/pull/4535#pullrequestreview-1168216154_

**Comment by Nuttapon43** [comment]
@Nuttapon43

**Comment by marmeladema** [comment]
Not sure what is the issue for. Closing for now. Feel free to re-open with a detailed description.

**Comment by Nuttapon43** [comment]
@marmeladema

**Comment by Nuttapon43** [comment]
#78
